title: 'Julian I. Kamil'
subtitle: 'etechcetera'
author: 'juliankamil'
bio: ''
description: 'News and opinions on science, technology, and pop culture'
logo: 'assets/img/Avatar - Rounded - BW - 790.jpg'
show_downloads: false
google_analytics:
theme: juliankamil.jekyll
locale: en_US
baseurl: ''
url: 'https://juliankamil.github.io'
github:
  is_user_page: true
  owner_url: "https://github.com/juliankamil"
future: true
twitter: "https://twitter.com/juliankamil"
instagram: "https://instagram.com/juliankamil"
email: "julian.kamil@gmail.com"