apiVersion: v1
entries:
  emma-app:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-12T19:51:07.810020594Z
    description: Emma App (SOE)
    digest: 66a48d2327a5125d94f518f0401c2d6fa5c5993fa05af8d45563f4dc1717babe
    icon: https://juliankamil.github.io/charts/emma-app/emma-icons-soe.png
    name: emma-app
    urls:
    - https://juliankamil.github.io/charts/emma-app/emma-app-0.1.0.tgz
    version: 0.1.0
  emma-db:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-12T19:51:07.850053957Z
    description: Emma DB
    digest: ab58b54bfd6ace97091b88dedfd6f3a02dea563e712d838f4c699278bfc37cdd
    icon: https://juliankamil.github.io/charts/emma-db/emma-icons-db.png
    name: emma-db
    urls:
    - https://juliankamil.github.io/charts/emma-db/emma-db-0.1.0.tgz
    version: 0.1.0
  emma-mongo:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-15T16:38:21.313990462Z
    description: Emma Mongo database.  This is a prerequisite used by the Emma App
      (SOE) to store conversation logs and context data occurring in the Emma UI application.  Please
      deploy and configure this database before deploying Emma App (SOE) and Emma
      UI applications.
    digest: bec334753f4769cedae1bc1db255fe7d3d786bb241af3c60f87a1a234266bd65
    icon: https://juliankamil.github.io/charts/emma-mongo/emma-icons-db.png
    name: emma-mongo
    urls:
    - https://juliankamil.github.io/charts/emma-mongo/emma-mongo-0.1.0.tgz
    version: 0.1.0
  emma-redis:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-15T16:38:21.320840602Z
    description: Emma Redis database.  This is a prerequisite used by the Emma App
      (SOE) to store context data of the user interacting with the Emma UI application.  Please
      deploy and configure this database before deploying Emma App (SOE) and Emma
      UI applications.
    digest: 37ec99cb35417e722ca2c0b397f5fcb522d35cfa841c02ad9f108b57454fdb8d
    icon: https://juliankamil.github.io/charts/emma-redis/emma-icons-db.png
    name: emma-redis
    urls:
    - https://juliankamil.github.io/charts/emma-redis/emma-redis-0.1.0.tgz
    version: 0.1.0
  emma-ui:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-12T19:51:07.863570342Z
    description: Emma UI application.  This application requires a working Emma App
      (SOE) and the corresponding database, Emma DB (MySQL).  Please deploy and configure
      both before deploying this application.
    digest: 7b6d35caca4842fa9e6579288bcfdb90e6cb3e0e78c79c58c2366a0389ac2889
    icon: https://juliankamil.github.io/charts/emma-ui/emma-icons-ui.png
    name: emma-ui
    urls:
    - https://juliankamil.github.io/charts/emma-ui/emma-ui-0.1.0.tgz
    version: 0.1.0
generated: 2018-11-12T19:51:07.8012107Z
